// flow-typed signature: c8c40c1889355017073855ae44b01a1f
// flow-typed version: <<STUB>>/apollo-server-micro_v^1.1.7/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-server-micro'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-server-micro' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-server-micro/dist/index' {
  declare module.exports: any;
}

declare module 'apollo-server-micro/dist/microApollo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-server-micro/dist/index.js' {
  declare module.exports: $Exports<'apollo-server-micro/dist/index'>;
}
declare module 'apollo-server-micro/dist/microApollo.js' {
  declare module.exports: $Exports<'apollo-server-micro/dist/microApollo'>;
}
