// flow-typed signature: da28d8ed48336c30eff20586ec18601b
// flow-typed version: <<STUB>>/babel-plugin-syntax-class-properties_v^6.13.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-syntax-class-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-syntax-class-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-syntax-class-properties/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-syntax-class-properties/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-syntax-class-properties/lib/index'>;
}
