// flow-typed signature: d43dddca4efcac0af5fc9d46485e9a29
// flow-typed version: <<STUB>>/conf_v^1.3.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'conf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'conf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'conf/index' {
  declare module.exports: $Exports<'conf'>;
}
declare module 'conf/index.js' {
  declare module.exports: $Exports<'conf'>;
}
