// flow-typed signature: 8341575d97ef1f1833539993505c9c43
// flow-typed version: <<STUB>>/graphql-subscriptions_v^0.5.8/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-subscriptions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-subscriptions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-subscriptions/dist/event-emitter-to-async-iterator' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/pubsub-engine' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/pubsub' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/with-filter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-subscriptions/dist/event-emitter-to-async-iterator.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/event-emitter-to-async-iterator'>;
}
declare module 'graphql-subscriptions/dist/index.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/index'>;
}
declare module 'graphql-subscriptions/dist/pubsub-engine.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/pubsub-engine'>;
}
declare module 'graphql-subscriptions/dist/pubsub.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/pubsub'>;
}
declare module 'graphql-subscriptions/dist/with-filter.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/with-filter'>;
}
