// flow-typed signature: 34b2039377debceae2303730644e580f
// flow-typed version: <<STUB>>/microrouter_v^3.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'microrouter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'microrouter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'microrouter/dist/index' {
  declare module.exports: any;
}

declare module 'microrouter/lib/index' {
  declare module.exports: any;
}

declare module 'microrouter/lib/index.test' {
  declare module.exports: any;
}

declare module 'microrouter/utils/index' {
  declare module.exports: any;
}

declare module 'microrouter/utils/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'microrouter/dist/index.js' {
  declare module.exports: $Exports<'microrouter/dist/index'>;
}
declare module 'microrouter/lib/index.js' {
  declare module.exports: $Exports<'microrouter/lib/index'>;
}
declare module 'microrouter/lib/index.test.js' {
  declare module.exports: $Exports<'microrouter/lib/index.test'>;
}
declare module 'microrouter/utils/index.js' {
  declare module.exports: $Exports<'microrouter/utils/index'>;
}
declare module 'microrouter/utils/index.test.js' {
  declare module.exports: $Exports<'microrouter/utils/index.test'>;
}
