// flow-typed signature: 5649dc6dbb9690749ccd6adfdd6d474d
// flow-typed version: <<STUB>>/micro-cors_v^0.0.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micro-cors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'micro-cors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'micro-cors/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'micro-cors/lib/index.js' {
  declare module.exports: $Exports<'micro-cors/lib/index'>;
}
