// flow-typed signature: 4ba89a2bbc892072bb8eaf285edfc683
// flow-typed version: <<STUB>>/onyx-contracts_v*/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'onyx-contracts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'onyx-contracts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'onyx-contracts/flow-typed/npm/web3-eth-contract_vx.x.x' {
  declare module.exports: any;
}

declare module 'onyx-contracts/flow-typed/npm/web3-utils_vx.x.x' {
  declare module.exports: any;
}

declare module 'onyx-contracts/src/constants' {
  declare module.exports: any;
}

declare module 'onyx-contracts/src/ens' {
  declare module.exports: any;
}

declare module 'onyx-contracts/src/index' {
  declare module.exports: any;
}

declare module 'onyx-contracts/src/staking' {
  declare module.exports: any;
}

declare module 'onyx-contracts/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'onyx-contracts/flow-typed/npm/web3-eth-contract_vx.x.x.js' {
  declare module.exports: $Exports<'onyx-contracts/flow-typed/npm/web3-eth-contract_vx.x.x'>;
}
declare module 'onyx-contracts/flow-typed/npm/web3-utils_vx.x.x.js' {
  declare module.exports: $Exports<'onyx-contracts/flow-typed/npm/web3-utils_vx.x.x'>;
}
declare module 'onyx-contracts/src/constants.js' {
  declare module.exports: $Exports<'onyx-contracts/src/constants'>;
}
declare module 'onyx-contracts/src/ens.js' {
  declare module.exports: $Exports<'onyx-contracts/src/ens'>;
}
declare module 'onyx-contracts/src/index.js' {
  declare module.exports: $Exports<'onyx-contracts/src/index'>;
}
declare module 'onyx-contracts/src/staking.js' {
  declare module.exports: $Exports<'onyx-contracts/src/staking'>;
}
declare module 'onyx-contracts/src/utils.js' {
  declare module.exports: $Exports<'onyx-contracts/src/utils'>;
}
