// flow-typed signature: fae093d53be8c23ae14b528986f5df8b
// flow-typed version: <<STUB>>/react-native-blockies_v^1.0.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-blockies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-blockies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-blockies/lib/Canvas' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-blockies/index' {
  declare module.exports: $Exports<'react-native-blockies'>;
}
declare module 'react-native-blockies/index.js' {
  declare module.exports: $Exports<'react-native-blockies'>;
}
declare module 'react-native-blockies/lib/Canvas.js' {
  declare module.exports: $Exports<'react-native-blockies/lib/Canvas'>;
}
