// flow-typed signature: cd6581fbfda8d08a4a6153028a1934f3
// flow-typed version: <<STUB>>/react-native-qrcode-scanner_v^0.0.28/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-qrcode-scanner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-qrcode-scanner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-qrcode-scanner/examples/default.android' {
  declare module.exports: any;
}

declare module 'react-native-qrcode-scanner/examples/default.ios' {
  declare module.exports: any;
}

declare module 'react-native-qrcode-scanner/examples/fullScreen.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-qrcode-scanner/examples/default.android.js' {
  declare module.exports: $Exports<'react-native-qrcode-scanner/examples/default.android'>;
}
declare module 'react-native-qrcode-scanner/examples/default.ios.js' {
  declare module.exports: $Exports<'react-native-qrcode-scanner/examples/default.ios'>;
}
declare module 'react-native-qrcode-scanner/examples/fullScreen.ios.js' {
  declare module.exports: $Exports<'react-native-qrcode-scanner/examples/fullScreen.ios'>;
}
declare module 'react-native-qrcode-scanner/index' {
  declare module.exports: $Exports<'react-native-qrcode-scanner'>;
}
declare module 'react-native-qrcode-scanner/index.js' {
  declare module.exports: $Exports<'react-native-qrcode-scanner'>;
}
