// flow-typed signature: 3e583377e1499f172011157b0632a929
// flow-typed version: <<STUB>>/web3-eth-contract_v^1.0.0-beta.34/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3-eth-contract'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3-eth-contract' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3-eth-contract/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3-eth-contract/src/index.js' {
  declare module.exports: $Exports<'web3-eth-contract/src/index'>;
}
