// flow-typed signature: 06121e9ed332648a7214f79e04474b10
// flow-typed version: <<STUB>>/web3-utils_v^1.0.0-beta.34/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3-utils/src/bloomFilter' {
  declare module.exports: any;
}

declare module 'web3-utils/src/index' {
  declare module.exports: any;
}

declare module 'web3-utils/src/soliditySha3' {
  declare module.exports: any;
}

declare module 'web3-utils/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3-utils/src/bloomFilter.js' {
  declare module.exports: $Exports<'web3-utils/src/bloomFilter'>;
}
declare module 'web3-utils/src/index.js' {
  declare module.exports: $Exports<'web3-utils/src/index'>;
}
declare module 'web3-utils/src/soliditySha3.js' {
  declare module.exports: $Exports<'web3-utils/src/soliditySha3'>;
}
declare module 'web3-utils/src/utils.js' {
  declare module.exports: $Exports<'web3-utils/src/utils'>;
}
